config/routes.rb
Rails.application.routes.draw do
    # Users
    post '/login' => 'users#login'
    get '/logout' => 'users#logout'
    get '/register' => 'users#register'
    get '/users/settings' => 'users#settings'
    post '/users/save' => 'users#create'
    post '/users/update' => 'users#update'

    # Apps
    get '/apps' => 'apps#index'
    get '/apps/create' => 'apps#create'
    get '/apps/delete/(:key)' => 'apps#delete'
    post '/apps/save' => 'apps#save'

    # API - Tags
    get '/api/v1/tags' => 'tags#index'
    get '/api/v1/tags/:id' => 'tags#single'

    # API - Locations
    get '/api/v1/locations' => 'locations#index'
    get '/api/v1/locations/search' => 'locations#search'
    get '/api/v1/locations/:id' => 'locations#single'
    delete '/api/v1/locations/:id' => 'locations#delete'

    # API - Owners
    get '/api/v1/owners' => 'owners#index'
    get '/api/v1/owners/:id/locations' => 'owners#locations'
    get '/api/v1/owners/:id' => 'owners#single'

    root :to => 'home#index'
end

app/models/user.rb
class User < ActiveRecord::Base
    has_secure_password

    validates :name, :presence => { :message => 'Du måste ange ditt namn.' }
    validates :email, :presence => { :message => 'Du måste ange din e-postadress.' }
    validates_uniqueness_of :email, :case_sensitive => false, :message => 'Den e-postadressen är redan upptagen.'
    validates :password, :presence => { :message => 'Du måste ange ett lösenord.' }, :on => :create

    attr_accessor :app
end

app/controllers/users_controller.rb
require 'securerandom'
require 'digest/sha2'

class UsersController < ApplicationController
    def create
        flash[:fields] = params

        user = User.new
        user.name = params[:name]
        user.email = params[:email]
        user.password = params[:password]

        user.validate()
        errors = user.errors

        app = App.new
        app.key = Digest::SHA1.new << user.email + SecureRandom.hex(8)
        app.title = params[:title]
        app.description = params[:description]

        app.validate()
        app.errors.each do |attr, error|
            errors.add(attr, error)
        end

        if errors.size() > 0
            flash[:notice] = errors

            return redirect_to register_path
        else
            user.save

            app.user_id = user.id
            app.save
        end

        session[:user] = user.id

        redirect_to '/apps'
    end

    def login
        require_guest

        flash[:fields] = params

        user = User.find_by(email: params[:email])
        if !user
            return redirect_to root_path, :notice => 'Fel användarnamn eller lösenord.'
        end

        user = user.authenticate(params[:password])
        if !user
            return redirect_to root_path, :notice => 'Fel användarnamn eller lösenord.'
        end

        session[:user] = user.id

        redirect_to apps_path
    end

    def logout
        require_login
        reset_session

        redirect_to root_path, :alert => 'Du är utloggad.'
    end

    def register
        require_guest
    end

    def settings
        require_login

        @user = User.find_by(id: session[:user])
    end

    def update
        require_login

        user = User.find_by(id: session[:user])
        user.name = params[:name]
        user.email = params[:email]

        if params[:password]
            user.password = params[:password]
        end

        is_valid = user.save

        if !is_valid
            flash[:notice] = user.errors
            flash[:fields] = params

            return redirect_to users_settings_path
        end

        redirect_to users_settings_path, alert: 'Dina inställningar är uppdaterade.'
    end
end

app/views/users/register.html.erb
    <div class="container">

        <h1>Registrera</h1>

        <form action="<%= url_for users_save_path %>" method="post">

            <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>" />

            <p class="text-danger">
                <%
                if flash[:notice]
                    flash[:notice].each do |attr, error|
                %>
                        <%= error.last %> <br>
                <%
                    end
                end
                %>
            </p>

            <label for="name">Ditt namn</label>
            <p>
                <input type="text" name="name" id="name" value="<%= get_field("name") %>" required>
            </p>

            <label for="email">Email</label>
            <p>
                <input type="email" name="email" id="email" value="<%= get_field("email") %>" required>
            </p>

            <label for="password">Lösenord</label>
            <p>
                <input type="password" name="password" id="password" required>
            </p>

            <label for="title">Namn på applikationen</label>
            <p>
                <input type="text" name="title" id="title" value="<%= get_field("title") %>" required>
            </p>

            <label for="description">Beskrivning av applikationen</label>
            <p>
                <textarea name="description" id="description" rows="8" cols="40" required><%= get_field("description") %></textarea>
            </p>

            <input type="submit" value="Registrera" class="btn btn-primary">

        </form>

    </div>

app/views/users/settings.html.erb
    <div class="container">

        <h1>Inställningar</h1>

        <form action="<%= url_for users_update_path %>" method="post">

            <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>" />

                <%
                if flash[:notice]
                %>
                <p class="text-danger">
                <%
                    flash[:notice].each do |attr, error|
                %>
                        <%= error.last %> <br>
                <%
                    end
                %>
                </p>
                <%
                elsif flash[:alert]
                %>
                    <p class="text-success">
                        <%= flash[:alert] %>
                    </p>
                <%
                end
                %>
            </p>

            <label for="name">Ditt namn</label>
            <p>
                <input type="text" name="name" id="name" value="<%= get_field("name") || @user.name %>" required>
            </p>

            <label for="email">Email</label>
            <p>
                <input type="email" name="email" id="email" value="<%= get_field("email") || @user.email %>" required>
            </p>

            <label for="password">Lösenord (lämna tomt om du inte vill ändra det)</label>
            <p>
                <input type="password" name="password" id="password">
            </p>

            <input type="submit" value="Uppdatera" class="btn btn-primary">

        </form>

    </div>