config/routes.rb
Rails.application.routes.draw do
    # Users
    post '/login' => 'users#login'
    get '/logout' => 'users#logout'
    get '/register' => 'users#register'
    get '/users/settings' => 'users#settings'
    post '/users/save' => 'users#create'
    post '/users/update' => 'users#update'

    # Apps
    get '/apps' => 'apps#index'
    get '/apps/create' => 'apps#create'
    get '/apps/delete/(:key)' => 'apps#delete'
    post '/apps/save' => 'apps#save'

    # API - Tags
    get '/api/v1/tags' => 'tags#index'
    get '/api/v1/tags/:id' => 'tags#single'

    # API - Locations
    get '/api/v1/locations' => 'locations#index'
    get '/api/v1/locations/search' => 'locations#search'
    get '/api/v1/locations/:id' => 'locations#single'
    delete '/api/v1/locations/:id' => 'locations#delete'

    # API - Owners
    get '/api/v1/owners' => 'owners#index'
    get '/api/v1/owners/:id/locations' => 'owners#locations'
    get '/api/v1/owners/:id' => 'owners#single'

    root :to => 'home#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        require_guest
    end
end

app/views/home/index.html.erb
    <div class="container">

        <h1>Logga in</h1>

        <form action="<%= url_for login_path %>" method="post">

            <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>" />

            <%
            if flash[:notice]
            %>
                <p class="text-danger">
                    <%= flash[:notice] %>
                </p>
            <%
            elsif flash[:alert]
            %>
                <p class="text-success">
                    <%= flash[:alert] %>
                </p>
            <%
            end
            %>

            <label for="email">Email</label>
            <p>
                <input type="email" name="email" id="email" value="<%= get_field("email") %>" required>
            </p>

            <label for="password">Lösenord</label>
            <p>
                <input type="password" name="password" id="password" required>
            </p>

            <p>
                <input type="submit" value="Logga in" class="btn btn-primary">
            </p>

        </form>

        <p>
            <%= link_to 'Registrera', register_path %>
        </p>

    </div>