config/routes.rb
Rails.application.routes.draw do
    # Users
    post '/login' => 'users#login'
    get '/logout' => 'users#logout'
    get '/register' => 'users#register'
    get '/users/settings' => 'users#settings'
    post '/users/save' => 'users#create'
    post '/users/update' => 'users#update'

    # Apps
    get '/apps' => 'apps#index'
    get '/apps/create' => 'apps#create'
    get '/apps/delete/(:key)' => 'apps#delete'
    post '/apps/save' => 'apps#save'

    # API - Tags
    get '/api/v1/tags' => 'tags#index'
    get '/api/v1/tags/:id' => 'tags#single'

    # API - Locations
    get '/api/v1/locations' => 'locations#index'
    get '/api/v1/locations/search' => 'locations#search'
    get '/api/v1/locations/:id' => 'locations#single'
    delete '/api/v1/locations/:id' => 'locations#delete'

    # API - Owners
    get '/api/v1/owners' => 'owners#index'
    get '/api/v1/owners/:id/locations' => 'owners#locations'
    get '/api/v1/owners/:id' => 'owners#single'

    root :to => 'home#index'
end

app/views/apps/create.html.erb
    <div class="container">

        <h1>Skapa ny applikation</h1>

        <form action="<%= url_for apps_save_path %>" method="post" novalidate>

            <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>" />

            <p class="text-danger">
                <%
                if flash[:notice]
                    flash[:notice].each do |attr, error|
                %>
                        <%= error.last %> <br>
                <%
                    end
                end
                %>
            </p>

            <label for="title">Namn på applikationen</label>
            <p>
                <input type="text" name="title" id="title" value="<%= get_field("title") %>" required>
            </p>

            <label for="description">Beskrivning av applikationen</label>
            <p>
                <textarea name="description" id="description" rows="8" cols="40" required><%= get_field("description") %></textarea>
            </p>

            <input type="submit" value="Skapa" class="btn btn-primary">

        </form>

    </div>

app/views/apps/index.html.erb
    <div class="container">

        <h1>API-nycklar</h1>

        <%
        if @users && @users.size() > 0
            @users.each do |user|
        %>

            <dl>
                <dt><%= user.app[:title] %></dt>
                <dd><%= simple_format(user.app[:description]) %></dd>
                <dd><b>Namn:</b> <%= user.name %></dd>
                <dd><b>E-post:</b> <%= user.email %></dd>
                <dd><b>Nyckel:</b> <%= user.app[:key] %></dd>
            </dl>

            <p>
                <%= link_to 'Radera', { :controller  => 'apps', :action => 'delete', :key => user.app[:key] }, :class => 'btn btn-danger' %>
            </p>

        <%
            end
        elsif @app
        %>

            <dl>
                <dt><%= @app.title %></dt>
                <dd><%= simple_format(@app.description) %></dd>
                <dd><b>Nyckel:</b> <%= @app.key %></dd>
            </dl>

            <%= link_to 'Radera', { :controller => 'apps', :action => 'delete' }, :class => 'btn btn-danger' %>

        <%
        else
        %>

            <p>
                Inga nycklar hittades.
            </p>

            <%
            if !is_admin
            %>
            <p>
                <%= link_to 'Skapa ny applikation', apps_create_path, :class => 'btn btn-success' %>
            </p>

        <%
            end
        end
        %>

    </div>