config/routes.rb
Rails.application.routes.draw do
    # Users
    post '/login' => 'users#login'
    get '/logout' => 'users#logout'
    get '/register' => 'users#register'
    get '/users/settings' => 'users#settings'
    post '/users/save' => 'users#create'
    post '/users/update' => 'users#update'

    # Apps
    get '/apps' => 'apps#index'
    get '/apps/create' => 'apps#create'
    get '/apps/delete/(:key)' => 'apps#delete'
    post '/apps/save' => 'apps#save'

    # API - Tags
    get '/api/v1/tags' => 'tags#index'
    get '/api/v1/tags/:id' => 'tags#single'

    # API - Locations
    get '/api/v1/locations' => 'locations#index'
    get '/api/v1/locations/search' => 'locations#search'
    get '/api/v1/locations/:id' => 'locations#single'
    delete '/api/v1/locations/:id' => 'locations#delete'

    # API - Owners
    get '/api/v1/owners' => 'owners#index'
    get '/api/v1/owners/:id/locations' => 'owners#locations'
    get '/api/v1/owners/:id' => 'owners#single'

    root :to => 'home#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>

<head>
    <meta charset="utf-8">
    <title>REST API</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">

    <%= stylesheet_link_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
</head>

<body>

    <div class="navbar-inverse">

        <div class="navbar-inner">

            <div class="container">

                <a class="navbar-brand" href="/">REST API</a>

                <% if is_signed_in? %>
                <ul class="nav navbar-nav navbar-right">
                    <li><%= link_to 'Inställningar', users_settings_path %></li>
                    <li><%= link_to 'Logga ut', logout_path %></li>
                </ul>
                <% end %>

            </div>

        </div>

    </div>

    <%= yield %>

</body>